spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.MySQLDialect

oauth:
  kakao:
    base-url: ${KAKAO_BASE_URL}
    app-key: ${KAKAO_APP_KEY}


jwt:
  secret: ${JWT_SECRET}