spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.MySQLDialect

  redis:
    host: ${REDIS_HOSTNAME}
    port: ${REDIS_PORT}

oauth:
  kakao:
    base-url: ${KAKAO_BASE_URL}
    app-key: ${KAKAO_APP_KEY}

  apple:
    base-url: ${APPLE_BASE_URL}
    app-key: ${APPLE_APP_KEY}

jwt:
  secret: ${JWT_SECRET}

springdoc:
  swagger-ui:
    groups-order: desc
    tags-sorter: alpha
    operations-sorter: method
    disable-swagger-default-url: true
    display-request-duration: true